#db:
#  image: mysql:latest
#  environment:
#    MYSQL_ROOT_PASSWORD: uned
#    MYSQL_DATABASE: healthmap
#    MYSQL_USER: uned
#    MYSQL_PASSWORD: uned
#  ports:
#    - "3306:3306"
#  volumes:
#   - ./db:/docker-entrypoint-initdb.d

web:
  image: tomcat:latest
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
#  environment:
#    JDBC_URL: jdbc:mysql://db:3306/HealthMap?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
#    JDBC_USER: admin
#    JDBC_PASS: admin
  ports:
   - "80:8080"
  volumes:
   - ./src/main/webapp/:/usr/local/tomcat/webapps/HealthMap
#    - db